### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc13x2

### Add to the source dirs
CONTIKI_TARGET_DIRS += launchpad/cc1312

### Include the common launchpad makefile
include $(PLATFORM_ROOT_DIR)/launchpad/Makefile.launchpad
