TI_XXWARE_PATH = lib/cc13x2-cc26x2-driverlib

CONTIKI_CPU_SOURCEFILES += smartrf-settings.c prop-mode.c prop-mode-tx-power.c

CFLAGS += -DCPU_FAMILY_CC13XX=1
CFLAGS += -DCPU_FAMILY_CC13X2=1

include $(CONTIKI_CPU)/Makefile.cc26x2-cc13x2
